### ISSUE TITLE
hoq ro solve "_check_and_prepare_data     raise TypeError('Expect data.index as DatetimeIndex')"

### ISSUE THREAD

**Issue by hanfon2020** [matplotlib/mplfinance#419]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.

```python
import os
import pandas as pd
import pandas_datareader as pdr
import matplotlib.pyplot as plt
#from mpl_finance import candlestick2_ochl
import mplfinance as mpf
df=pd.read_csv('d:/stockdata/ch5/600895.csv',index_col='Date')
print(df)
mpf.plot(df,type='candle')
```

```
runfile('C:/Users/USER/untitled4.py', wdir='C:/Users/USER')
                 High        Low       Open      Close    Volume  Adj Close
Date                                                                       
2019-01-02  16.330000  14.710000  15.060000  15.930000  75979904  15.739503
2019-01-03  16.650000  15.310000  15.780000  16.240000  94733382  16.045795
2019-01-04  16.580000  15.600000  15.700000  16.299999  68985635  16.105078
2019-01-07  16.650000  15.600000  15.700000  16.290001  59222671  16.095200
2019-01-08  16.559999  15.810000  16.280001  16.040001  55522302  15.848187
2019-01-09  16.330000  15.750000  16.020000  16.020000  52641127  15.828426
2019-01-10  16.110001  15.120000  15.880000  15.200000  53202090  15.018232
2019-01-11  15.800000  15.060000  15.200000  15.560000  42057493  15.373927
2019-01-14  16.080000  15.350000  15.670000  15.460000  43255147  15.275124
2019-01-15  15.640000  15.090000  15.400000  15.540000  31687291  15.354166
2019-01-16  16.170000  15.460000  15.750000  15.710000  44711686  15.522133
2019-01-17  17.049999  15.600000  15.600000  16.980000  86309543  16.776945
2019-01-18  16.799999  16.049999  16.719999  16.290001  62198832  16.095200
2019-01-21  16.530001  15.920000  16.219999  16.400000  38675827  16.203882
2019-01-22  16.910000  16.219999  16.299999  16.360001  47087722  16.164360
2019-01-23  16.680000  15.910000  16.360001  16.400000  40190374  16.203882
2019-01-24  16.650000  15.930000  16.650000  16.070000  39457212  15.877828
2019-01-25  16.040001  15.270000  15.920000  15.330000  42175769  15.146678
2019-01-28  15.570000  15.210000  15.500000  15.350000  21769886  15.166439
2019-01-29  15.500000  14.180000  15.270000  14.540000  31401261  14.366125
2019-01-30  14.770000  14.330000  14.490000  14.370000  16274136  14.198157
2019-01-31  14.750000  13.580000  14.690000  13.800000  32695437  13.634974
Traceback (most recent call last):

  File "C:\Users\USER\untitled4.py", line 17, in <module>
    mpf.plot(df,type='candle')

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplfinance\plotting.py", line 298, in plot
    dates,opens,highs,lows,closes,volumes = _check_and_prepare_data(data, config)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mplfinance\_arg_validators.py", line 30, in _check_and_prepare_data
    raise TypeError('Expect data.index as DatetimeIndex')

TypeError: Expect data.index as DatetimeIndex
```

**Comment by DanielGoldfarb** [comment]
Try adding `parse_date=True` to your call to read_csv:

```python
df=pd.read_csv('d:/stockdata/ch5/600895.csv',index_col='Date',parse_dates=True)
```

**Comment by hanfon2020** [comment]
thanks!  it well done.

**Comment by DanielGoldfarb** [comment]
you're welcome
