### ISSUE TITLE
why can do plot chart?

### ISSUE THREAD

**Issue by hanfon2020** [matplotlib/mplfinance#437]
i want to plot interday k-charts,  first read data from sqlite3

```python 
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
conn = sqlite3.connect('indexfuture.sqlite') 
cursor = conn.cursor() # 
strtemp= "SELECT * FROM table1"
df = pd.read_sql(strtemp,conn)
iday=df.loc[0:2383575,:]
print(iday)
```

it's outpupt like below

```bash
runfile('C:/Users/USER/sqlplot.py', wdir='C:/Users/USER')
                day      time   open   high    low  close  volume
0        2001/01/02  08:46:00   4702   4719   4700   4710      67
1        2001/01/02  08:47:00   4703   4729   4703   4729      30
2        2001/01/02  08:48:00   4723   4744   4723   4738      24
3        2001/01/02  08:49:00   4730   4740   4730   4737      25
4        2001/01/02  08:50:00   4735   4735   4730   4730      21
            ...       ...    ...    ...    ...    ...     ...
2383571  2021/07/30  13:41:00  17159  17163  17159  17162     350
2383572  2021/07/30  13:42:00  17164  17170  17163  17168     412
2383573  2021/07/30  13:43:00  17167  17173  17167  17173     466
2383574  2021/07/30  13:44:00  17172  17175  17166  17173     507
2383575  2021/07/30  13:45:00  17171  17178  17171  17173    1030

[2383576 rows x 7 columns
```
and then call  mplfinance function

```python
import pandas as pd
import matplotlib.pyplot as plt
import mplfinance as mpf
import sqlite3
conn = sqlite3.connect('indexfuture.sqlite') 
currsor = conn.cursor() 
strtemp= "SELECT * FROM table1"
df = pd.read_sql(strtemp,conn)
iday=df.loc[0:2383575,:]
mpf.plot(iday,type='candle')
```

it's error message like that 

```python
runfile('C:/Users/USER/sqlplot.py', wdir='C:/Users/USER')
Traceback (most recent call last):

  File "C:\Users\USER\sqlplot.py", line 10, in <module>
    import mplfinance as mpf

  File "C:\Users\USER\mplfinance.py", line 14, in <module>
    df=pd.read_csv('c:/users/user/iris.csv',index_col='Date',parse_dates=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)

  File "pandas\_libs\parsers.pyx", line 529, in pandas._libs.parsers.TextReader.__cinit__

  File "pandas\_libs\parsers.pyx", line 749, in pandas._libs.parsers.TextReader._get_header

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 0: invalid start by
```

i have checked by conda list ,  mplfinace has been setup .......
i have correct  `df = pd.read_sql(strtemp,conn)` to `df = pd.read_sql(strtemp,conn,parse_dates=True)`, but same error message output.

so , how could i do that?

**Comment by DanielGoldfarb** [comment]
> First, I modify the database field to merge the two fields of date and time into one field (day+time--->Date)

This is the correct solution.  I am glad you found it.  Let us know if you have any more questions.
