### ISSUE TITLE
Bug Report:

### ISSUE THREAD

**Issue by starleex0506** [matplotlib/mplfinance#56]
Traceback (most recent call last):
  File "d:/用户目录/Desktop/股票测试/MySql_rd.py", line 87, in <module>
    mpf.plot(iday,type='candle',mav=(5,13,21,34,55),volume=True)
  File "D:\Anaconda3\lib\site-packages\mplfinance\plotting.py", line 35, in decorator
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\mplfinance\plotting.py", line 154, in plot
    dates,opens,highs,lows,closes,volumes = _check_and_prepare_data(data)
  File "D:\Anaconda3\lib\site-packages\mplfinance\_arg_validators.py", line 29, in _check_and_prepare_data
    opens   = data['Open'].values
  File "D:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Open'

??? Open -----must be upper case ???

**Comment by DanielGoldfarb** [comment]
Yes, the column names are case sensitive, and must be:

    'Open', 'High', 'Low', 'Close', and optionally 'Volume'

[See this solution here](https://github.com/matplotlib/mplfinance/issues/23#issuecomment-581518428) for how you can easily remap your column names.
