### ISSUE TITLE
Error in module of Python 3.11.3, Pmw, BLT.

### ISSUE THREAD

**Issue by Blessvskp** [matplotlib/mplfinance#615]
I am using python 3.11.3. I am building a stock market package in python. I need menus in that package. For creating menus I want to use PMW package with tinker. 

To try my first steps, I used the code snippet at : https://www.slac.stanford.edu/grp/cd/soft/pmw/blt/python/html/HelloBLT.html
When I ran this script, I am getting this error:

"Traceback (most recent call last):
  File "D:\PYTHON_3.11.3\Lib\site-packages\Pmw\Pmw_2_1_1\lib\PmwBlt.py", line 103, in __del__
    self.tk.call(_vectorCommand, 'destroy', self._name)
_tkinter.TclError: invalid command name "::blt::vector""

Any help please

**Comment by DanielGoldfarb** [comment]
Is that the *entire* traceback??

**Comment by Blessvskp** [comment]
Entire traceback:
"D:\PyProgFiles\ChatGPT>PY D:\PyProgFiles\ChatGPT\PracticeModules\pMW_SNIPPETS\PMW1.py
Traceback (most recent call last):
  File "D:\PyProgFiles\ChatGPT\PracticeModules\pMW_SNIPPETS\PMW1.py", line 57, in <module>
    vector_x = Pmw.Blt.Vector()
               ^^^^^^^^^^^^^^^^
  File "D:\PYTHON_3.11.3\Lib\site-packages\Pmw\Pmw_2_1_1\lib\PmwBlt.py", line 99, in __init__
    self.tk.call(_vectorCommand, 'create', self._name)
_tkinter.TclError: invalid command name "::blt::vector"
Exception ignored in: <function Vector.__del__ at 0x0000026BF5A22FC0>
Traceback (most recent call last):
  File "D:\PYTHON_3.11.3\Lib\site-packages\Pmw\Pmw_2_1_1\lib\PmwBlt.py", line 103, in __del__
    self.tk.call(_vectorCommand, 'destroy', self._name)
_tkinter.TclError: invalid command name "::blt::vector""

**Comment by Blessvskp** [comment]
Hello Daniel,

Greetings

I posted entire trace back on Github in reply to you.

May I request you to please check it.

Regards

Bless

**Comment by DanielGoldfarb** [comment]
I am happy to help, even though (you realize) this exception has *nothing to do with mplfinance*.  I am not familiar the PMW package, however it is clear, from the traceback, that the function `Pmw.Blt.Vector()` does not exist in that package.

Have you taken the time to go through [**a Blt tutorial such as this**](https://www.slac.stanford.edu/grp/cd/soft/pmw/blt/tutorial.html)?

It appears that, while `Pmw.Blt.Vector` is indeed a class, it is *not* instatiated via `Pmw.Blt.Vector()`
I would also recommend *not* using chatGPT to write code.  More often than not it gets it wrong, and in the end you are forced none-the-less to actually learn the package or language for which you are trying to write code.

Perhaps your question would be better of posted on [**The BLT Toolkit Discussion/Help page**](https://sourceforge.net/p/blt/discussion/58931/) or on stackoverflow.  But I do *strongly* recommend that you take the time to work through a tutorial and other PMW and BLT documentation first (if you have not already), so that you can actually learn how to make menus, and then (if necessary, if you still have a question, then) your question can be asked in a much more specific manner (rather than just "I'm getting this error ... please help").

**Comment by Blessvskp** [comment]
Dear Danial,

Thank you for your very kind reply.

I am a quite busy person.  I am finding it very difficult to devote time to
different things.

I am on one side,  trying to learn PINE script.  I am trying to merge 2 or
3 indicators in pine script.  So far I couldn't succeed. I am learning.

On the other hand, I want to construct candle chart with menus for replay
etc. I have seen on sourceforge that you are helping many people. It is
highly appreciated. Great service to mankind!

In one such posts,  I saw you that you solved similar problem. The link to
it is:

https://github.com/matplotlib/mplfinance/issues/348

The problem that I am facing in this code is that @pipreaper pulled the
data (get_ticker_history) from Yahoo.

Where as, I want to pull data from CSV file on my laptop. I don't know how
to do it. Kindly help me in this regard. This will solve my big problem.
Then, hopefully  I will be able to work out the rest with the help of you
or help from others.

Kindly consider my request and oblige.
I shall be grateful to you.

With best regards.

Bless

**Comment by DanielGoldfarb** [comment]
As noted above, this question is about [**package pmw**](https://pypi.org/project/Pmw/), not mplfinance, and therefore is not appropriate for this forum.
